language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
 
matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty

install:
  - dotnet restore
script:
  - dotnet test
notifications:
  email:
    on_success: never
    on_failure: always
