language: csharp
mono: none
dotnet: 3.0.0
dist: trusty
script:
 - dotnet restore
 
matrix:
  include:
    - dotnet: 3.0.0
      mono: none
      dist: trusty

install:
  - dotnet restore
script:
  - dotnet test ./src/Tests/SvarnyJunak.CeskeObce.DataParser.Test
  - dotnet test ./src/Tests/SvarnyJunak.CeskeObce.Web
notifications:
  email:
    on_success: never
    on_failure: always
